version: 2.1
orbs:
  docker: circleci/docker@1.0.1
workflows:
  push:
    jobs:
      - build
      - phpunit:
          requires:
            - build
      - php-cs-fixer:
          requires:
            - build
      - security-checker:
          requires:
            - build
      - phpstan:
          requires:
            - build
      - deptrac:
          requires:
            - build
jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: smudja/etl
          tag: '$CIRCLE_SHA1,latest'
      - run:
          name: Save Docker images
          command: |
            mkdir docker-cache
            docker save -o docker-cache/$CIRCLE_SHA1.tar smudja/etl:$CIRCLE_SHA1
            docker save -o docker-cache/latest.tar smudja/etl:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache
  phpunit:
    executor: docker/docker
    steps:
      - docker_run:
          description: Run phpunit
          command: vendor/bin/phpunit
  php-cs-fixer:
    executor: docker/docker
    steps:
      - docker_run:
          description: Run php-cs-fixer
          command: vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no
  security-checker:
    executor: docker/docker
    steps:
      - docker_run:
          description: Run security-checker
          command: vendor/bin/security-checker security:check
  phpstan:
    executor: docker/docker
    steps:
      - docker_run:
          description: Run phpstan
          command: vendor/bin/phpstan analyze
  deptrac:
    executor: docker/docker
    steps:
      - docker_run:
          description: Run deptrac
          command: vendor/bin/deptrac
commands:
  docker_run:
    description: Run a docker command inside the image built in the build step
    parameters:
      description:
        type: string
        description: A description for the step
      command:
        type: string
        description: The command to run inside the docker image
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: << parameters.name >>
          command: |
            docker load < docker-cache/latest.tar
            docker run smudja/etl:latest << parameters.command >>
