version: 2.1
orbs:
  docker: circleci/docker@1.0.1
workflows:
  push:
    jobs:
      - build
      - phpunit:
          requires:
            - build
      - php-cs-fixer:
          requires:
            - build
      - security-checker:
          requires:
            - build
      - phpstan:
          requires:
            - build
      - deptrac:
          requires:
            - build
jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: smudja/etl
          tag: '$CIRCLE_SHA1,latest'
      - run:
          name: Save Docker images
          command: |
            mkdir docker-cache
            docker save -o docker-cache/$CIRCLE_SHA1.tar smudja/etl:$CIRCLE_SHA1
            docker save -o docker-cache/latest.tar smudja/etl:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache
  phpunit:
    executor: docker/docker
    steps:
      - import_image
      - run:
          name: Run tests
          command: |
              docker run --name app smudja/etl:latest vendor/bin/phpunit --log-junit results.xml
      - run:
          name: Copy test results
          when: always
          command: |
              mkdir -p test-results/phpunit
              docker cp app:/app/results.xml test-results/phpunit
      - store_test_results:
          path: test-results
  php-cs-fixer:
    executor: docker/docker
    steps:
      - import_image
      - run:
          name: Run cs fixer
          command: |
            mkdir -p test-results/php-cs-fixer
            docker run --name app smudja/etl:latest vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no --format junit > test-results/php-cs-fixer/results.xml
      - store_test_results:
          path: test-results
  security-checker:
    executor: docker/docker
    steps:
      - import_image
      - run:
          name: Run security checker
          command: docker run smudja/etl:latest vendor/bin/security-checker security:check
  phpstan:
    executor: docker/docker
    steps:
      - import_image
      - run:
          name: Run static analysis
          command: |
            mkdir -p test-results/phpstan
            docker run --name app smudja/etl:latest vendor/bin/phpstan analyze --error-format junit --no-progress > test-results/phpstan/results.xml
      - store_test_results:
          path: test-results
  deptrac:
    executor: docker/docker
    steps:
      - import_image
      - run:
          name: Run dependency analysis
          command: |
            mkdir -p test-results/deptrac
            docker run --name app smudja/etl:latest /bin/sh -o pipefail -c "vendor/bin/deptrac --formatter-junit=true --formatter-junit-dump-xml=results.xml ; cat results.xml" > test-results/deptrac/results.xml
      - store_test_results:
          path: test-results
commands:
  import_image:
    description: Import the docker image from the build step
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image
          command: docker load < docker-cache/latest.tar
