version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: smudja/etl
          tag: '$CIRCLE_SHA1,latest'
      - run:
          name: Save Docker images
          command: |
            mkdir docker-cache
            docker save -o docker-cache/$CIRCLE_SHA1.tar smudja/etl:$CIRCLE_SHA1
            docker save -o docker-cache/latest.tar smudja/etl:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache
  phpunit:
    executor: docker/docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            docker load < docker-cache/latest.tar
            docker run -d smudja/etl:latest vendor/bin/phpunit

workflows:
  push:
    jobs:
      - build
      - phpunit:
          requires:
            - build
